secretGenerator:
  - name: mysql-pass
    literals:
      - password=blaat12345
      
resources:
  - wordpress-db-persistentvolumeclaim.yaml
  - wordpress-db-deployment.yaml
  - wordpress-db-service.yaml
  - wordpress-app-namespace.yaml
  - wordpress-app-persistentvolumeclaim.yaml
  - wordpress-app-deployment.yaml
  - wordpress-app-service.yaml
  - wordpress-app-ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
