apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: wordpress
  annotations:
  #cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  #tls:
  #- hosts:
  #  - wordpress-ccc-poc.centric.eu
  #  secretName: tls-wordpress
  rules:
    - host: wordpress-ccc-poc.centric.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-service
                port:
                  number: 80
