apiVersion: v1
kind: Secret
metadata:
  name: wordpress
  namespace: default 
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/pderuiter/wordpress
  password: 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
  username: not-used
